Display image detail page
summer17-csc648-team1/Warehaus pull request #11
Opened 2017-07-23 06:12 UTC by raymondlf

Finish editing the page. 
Add test image testing.jpg under webroot/img

2017-07-24 00:05 UTC, runongirlrunon requested changes
Thanks @raymondlf, just a few small changes (removing unnecessary comments and a couple other lines we don't need) and then it should be good to go!

2017-07-24 00:05 UTC, runongirlrunon commented on src/Template/Pages/detail.ctp
> +                    <a target="_blank" href="https://www.google.com"><button >Contact Owner</button></a>
rather than sending this to an external website, you can just use `#` to stay on the current page until the `Message` module is implemented.

2017-07-24 00:05 UTC, runongirlrunon commented on src/Template/Pages/detail.ctp
> +$cakeDescription = 'CakePHP: the rapid development PHP framework';
You can take this line and the surrounding extra whitespace out--it's not used anymore.

2017-07-24 00:05 UTC, runongirlrunon commented on src/Template/Pages/detail.ctp
> +            /*height:320px;*/
These lines can be taken out if they're just comments.

2017-07-24 00:05 UTC, runongirlrunon commented on src/Template/Pages/detail.ctp
> +            /*            border-collapse: collapse;
These comments, too.

2017-07-24 06:28 UTC, raymondlf commented
Changes made. Comments removed. Button is pointing to the current page.

2017-07-24 18:19 UTC, runongirlrunon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Details view & controller](https://trello.com/c/pVDMUQCd/15-details-view-controller)

2017-07-26 00:40 UTC, runongirlrunon approved these changes
LGTM thank you!

2017-07-26 00:40 UTC, merged