added home and login page
summer17-csc648-team1/Warehaus pull request #8
Opened 2017-07-21 19:34 UTC by jhuang28

@runongirlrunon @JReed21 home page and login page created

2017-07-21 21:53 UTC, JReed21 requested changes
You don't need to link to the libraries over the web, we have bootstrap, jquery, and bootstraps javascript in our local folders. 

<?= $this->Html->css('bootstrap.css') ?>
<?= $this->Html->script('jquery-3.2.1.min.js') ?>


Hard coding the ctp file into href is fine for now since we have no created controllers BUT if you are working on the login page you must create a login controller to handle the authorization and login logic

2017-07-21 23:58 UTC, jhuang28 commented
@JReed21 took out most href, pages still look fine

2017-07-22 03:03 UTC, runongirlrunon commented
@jhuang28 please merge in the master branch and fix the merge conflicts.

2017-07-22 05:45 UTC, jhuang28 commented
@JReed21 took out most href, pages look fine, checkboxes were replaced by radios.

2017-07-23 23:45 UTC, runongirlrunon commented
@JReed21 could you re-review for the changes you requested?

2017-07-24 01:23 UTC, runongirlrunon requested changes

2017-07-24 01:23 UTC, runongirlrunon commented on src/Template/Pages/home.ctp
>  $cakeDescription = 'CakePHP: the rapid development PHP framework';
This line can be removed, as it's not used anymore.

2017-07-24 01:23 UTC, runongirlrunon commented on src/Template/Pages/login.ctp
> +$cakeDescription = 'CakePHP: the rapid development PHP framework';
Same here.

2017-07-24 18:19 UTC, runongirlrunon commented
![](https://github.trello.services/images/mini-trello-icon.png) [Login view & controller](https://trello.com/c/hg9MQR12/9-login-view-controller)

2017-07-24 21:31 UTC, JReed21 submitted a review, later dismissed

2017-07-24 22:01 UTC, jhuang28 commented
@runongirlrunon @JReed21 homepage and login page are updated; these two pages now can connect to each other. and if register.ctp is in Pages folder then they can connect to register page as well

2017-07-26 00:23 UTC, runongirlrunon approved these changes

2017-07-26 00:36 UTC, runongirlrunon commented
Note: the default template has an unnecessary green bar across the top but I'm going to ignore that for now and write a card to clean that up later.

2017-07-26 00:36 UTC, merged